Готовая домашняя работа
sokolov-v-a/learn-homework-1 pull request #1
Opened 2023-11-27 20:40 UTC by sokolov-v-a

2023-11-30 12:16 UTC, n05tr0m0 requested changes
Молодец, что сдал домашку.
Посмотри комментарии, попробуй использовать то, что я посоветовал.
Когда сделаешь коммиты с исправлениями, опять скинь в бота эту ссылку, чтобы я мог проверить свежие изменения.

2023-11-30 12:16 UTC, n05tr0m0 commented on 1_if1.py
> +    what_should__do = "учиться в детском саду"
Можно не вводить эту переменную, а сразу возращать результат ключевым словом `return`

2023-11-30 12:16 UTC, n05tr0m0 commented on 1_if1.py
> +    what_should__do = "учиться в детском саду"
```python
def main(age):
    if age < 2:
        return "Вы таки родились!"
    elif 2 <= age < 7:
        return "Вы должны быть в саду!"
    elif 7 <= age < 18:
        return "Вы должны быть в школе!"
    elif 18 <= age < 23:
        return "Вы должны быть в ВУЗе!"
    elif 22 <= age < 65:
        return "Вы должны уже работать!"
    elif 65 <= age < 99:
        return "Вы должны уже быть на пенсии"


if __name__ == "__main__":
    input_age = int(input("Enter your age: "))
    result = main(input_age)
    print(result)
```

2023-11-30 12:16 UTC, n05tr0m0 commented on 2_if2.py
> +    if not type(str1) is str or not type(str2) is str:
Для проверки соответсвия типов в python есть ключевое слово `isinstance()`
Так же тут надо проверять оба аргумента на то, что они строки, поэтому необходимо использовать `and`, а не `or`.
```python
if isinstance(input_1, str) and isinstance(input_2, str):
```

2023-11-30 12:16 UTC, n05tr0m0 commented on 2_if2.py
> +    elif len_str1 > len_str2:
Так же не хватает сравнения, что строки разные.

2023-11-30 12:16 UTC, n05tr0m0 commented on 2_if2.py
> +    elif len_str1 > len_str2:
И в добавок это условие не всегда будет выполняться. Подумай почему.

2023-11-30 12:16 UTC, n05tr0m0 commented on 3_for.py
> +def count_sum_sold(items_sold):
В место этой функции можно использовать встроенную функцию `sum()`

2023-11-30 12:16 UTC, n05tr0m0 commented on 3_for.py
> +    print(f"среднее количество продаж всех товаров - {avg_all_sales}")
Молодец, что сделал.

Можно упросить добавив дополнительный список, куда будем класть все продажи.

```python
def solution_with_list():
    products = [
        {'product': 'iPhone 12', 'items_sold': [363, 500, 224, 358, 480, 476, 470, 216, 270, 388, 312, 186]},
        {'product': 'Xiaomi Mi11', 'items_sold': [317, 267, 290, 431, 211, 354, 276, 526, 141, 453, 510, 316]},
        {'product': 'Samsung Galaxy 21', 'items_sold': [343, 390, 238, 437, 214, 494, 441, 518, 212, 288, 272, 247]},
    ]
    all_sales = []
    for product in products:
        # переменные ниже, сделаны для удобства читаемости кода
        product_name = product['product']
        sales = product['items_sold']
        total_sales = sum(sales)
        avg_sales = total_sales / len(sales)
        all_sales.extend(sales)
        print(f"Продукт: {product_name}, кол-во продаж: общие - {total_sales}, средние - {avg_sales:.0f}")
    total_sales = sum(all_sales)
    avg_sales = total_sales / len(products)
    print(f"Суммарное количество продаж всех товаров: {total_sales}")
    print(f"Среднее количество продаж всех товаров: {avg_sales}")
    ```
    
Таким образом мы будем использовать всего один цикл `for`

2023-11-30 12:16 UTC, n05tr0m0 commented on 7_exception2.py
> +    except TypeError:
Можно указывать исключения через запятую

```python
def discounted(price, discount, max_discount=20):
    try:
        price = abs(float(price))
        discount = abs(float(discount))
        max_discount = abs(int(max_discount))
    except (ValueError, TypeError) as err:
        return f"Введены не корректные данные, повторите ввод. Ошибка: {err}"
    if max_discount >= 100:
        return f"Слишком большая максимальная скидка. Она не может быть больше или равна 100%!"
    if discount >= max_discount:
        return price
    return price - (price * discount / 100)

```

2023-11-30 12:16 UTC, n05tr0m0 commented on 8_ephem_bot.py
> +      else:
А если будет список из тысяч планет, как поступишь?

В такис случаях надо делать проверку, есть ли нужное нам поле в объекте.
Для этого необхдимо воспользоваться встроенными в язык функциями `hasattr()` и `getattr()`

Подумай, как это можно реализовать, если не придумаешь, напиши мне, я подскажу.

2023-12-02 05:20 UTC, sokolov-v-a commented on 2_if2.py
> +    elif len_str1 > len_str2:
Переделал, неправильно прочитал задание

2023-12-02 05:47 UTC, sokolov-v-a commented on 7_exception2.py
> +    except TypeError:
Спасибо, ок. Обработал каждый exception, чтобы было больше деталей по ошибке, но соглашусь тут их логичнее объединить.

2023-12-04 12:28 UTC, n05tr0m0 requested changes
ещё немного

2023-12-04 12:28 UTC, n05tr0m0 commented on 1_if1.py
> +  elif(age < 120):
а зачем скобки?

2023-12-04 12:28 UTC, n05tr0m0 commented on 1_if1.py
> +  elif(age < 120):
```python
def main(age):
    if age < 2:
        return "Вы таки родились!"
    elif 2 <= age < 7:
        return "Вы должны быть в саду!"
    elif 7 <= age < 18:
        return "Вы должны быть в школе!"
    elif 18 <= age < 23:
        return "Вы должны быть в ВУЗе!"
    elif 22 <= age < 65:
        return "Вы должны уже работать!"
    elif 65 <= age < 99:
        return "Вы должны уже быть на пенсии"


if __name__ == "__main__":
    input_age = int(input("Enter your age: "))
    result = main(input_age)
    print(result)
```

2023-12-04 12:28 UTC, n05tr0m0 commented on 2_if2.py
> +      elif str2 == 'learn':
Это условие не всегда будет выполняться, потому что вторая строка будет меньше первой, но будет 'learn', при этом ты получишь цифру 2.

2023-12-04 12:28 UTC, n05tr0m0 commented on 2_if2.py
> +      elif str2 == 'learn':
```python
def main(input_1, input_2):
    if isinstance(input_1, str) and isinstance(input_2, str):
        if input_1 == input_2:
            return 1
        elif input_1 != input_2 and input_2 == 'learn':
            return 3
        elif input_1 != input_2 and len(input_1) > len(input_2):
            return 2
    return 0


if __name__ == "__main__":
    print(main(1, 2))
    print(main(1, "2"))
    print(main("1", 2))
    print(main("python", "learn"))
    print(main("string", "string"))
    print(main("learn_python", "course"))
```

2023-12-04 12:28 UTC, n05tr0m0 commented on 7_exception2.py
> +    price = abs(price)
А зачем разделять выполнение сразу нескольких преобразований?

Вот так:
```python
def discounted(price, discount, max_discount=20):
    try:
        price = abs(float(price))
        discount = abs(float(discount))
        max_discount = abs(int(max_discount))
    except (ValueError, TypeError) as err:
        return f"Введены не корректные данные, повторите ввод. Ошибка: {err}"
    if max_discount >= 100:
        return f"Слишком большая максимальная скидка. Она не может быть больше или равна 100%!"
    if discount >= max_discount:
        return price
    return price - (price * discount / 100)


if __name__ == "__main__":
    print(discounted(100, 2))
    print(discounted(100, "3"))
    print(discounted("100", "4.5"))
    print(discounted("five", 5))
    print(discounted("сто", "десять"))
    print(discounted(100.0, 5, max_discount="10"))
    print(discounted(100.0, 5, max_discount="десять"))
    print(discounted(100, 10, max_discount=150))

```

2023-12-06 09:10 UTC, n05tr0m0 approved these changes

2023-12-06 09:11 UTC, merged